trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**'

jobs:

- job: 'Tests'
  pool:
    vmImage: $(image)
  timeoutInMinutes: 360
  strategy:
    maxParallel: 9  
    matrix:
      'windows-2022':
        image: windows-2022
      'windows-2019':
        image: windows-2019
      'ubuntu-18.04':
        image: ubuntu-18.04
      'ubuntu-20.04':
        image: ubuntu-20.04
      'macOS-11':
        image: macOS-11
      'macOS-10.15':
        image: macOS-10.15

  steps:
  - bash: |
      set -eu; set -o pipefail
      cd Universe.LzmaDecompressor.Tests
      dotnet test -c Release 2>&1 | tee $(System.ARTIFACTSDIRECTORY)/test.log
    displayName: 'Tests'


  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

